#!/bin/csh
#SBATCH --job-name=ALMaSSjob_sensitivity
#SBATCH --partition=q28
#SBATCH --ntasks=1
#SBATCH --mem=256G
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=26
#SBATCH --time=24:00:00

echo "========= Job started at `date` =========="
sh /home/ldalby/workspace/Goose/SensitivityAnalysis/StartSensitivityAnalysis.sh
echo "========= Job finished at `date` =========="
#