---
title: "Goose parameter fitting"
author: "Lars Dalby"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 8)
```

```{r load, echo=FALSE,message=FALSE, warning=FALSE, include=FALSE}
# 'rgl',
packs = c('data.table', 'ralmass', 'ggplot2', 'RColorBrewer', 'knitr',  'stringr', 'viridis', 'ggthemes')
sapply(packs, FUN = require, character.only = TRUE)
pathtodirs = 'e:/almass/WorkDirectories/Goose'
knitr::opts_chunk$set(echo = FALSE)
# Read in the config so we can print the default values onto the plots
cfg = readLines('~/git/ALMaSS_inputs/GooseManagement/Vejlerne/TIALMaSSConfig.cfg')
resultfilename = 'GooseParameterFitting_2017-06-01.txt'

```

File: `r resultfilename` 

A round with +-25% of default parameter value (where possible).
    
* Initial fitting after major code update. 



## Plots
The **Individual** panel is showing the individual fits (raw values) and the **Overall** panel is showing the average sum of the squared species specific fits. Grey vertical line is showing the default value.

```{r Remodel, echo=FALSE}
se = function(x) sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))
remodel = function(res, type = "minmax") {
	res[c(grep('PF', FitType), grep('PT', FitType), grep('Pinkfoot', FitType)), Species:='Pinkfoot']
  res[FitType == 'Weightfit', Species:='Pinkfoot']	
	res[c(grep('BN', FitType), grep('BT', FitType), grep('Barnacle', FitType)), Species:='Barnacle']
	res[c(grep('GL', FitType), grep('GT', FitType), grep('Greylag', FitType)), Species:='Greylag']
	res[FitType %in% c('BarnacleFit', 'GreylagFit', 'PinkfootFit'), FitType:='OverallFit']
	res[!FitType %in% c('Weightfit', 'OverallFit'), FitType:=str_sub(FitType, end = -3)]
	if(type == "minmax"){
	 res[, c("mean", "min", "max") := .(mean(Fit), min(Fit), max(Fit)), by = .(Parameter, Species, Value, FitType)] 
	}
	if(type == "sd"){
    res[, c("mean", "min", "max") := .(mean(Fit), mean - sd(Fit), mean + sd(Fit)), by = .(Parameter, Species, Value, FitType)]	  
	}
	if(type == "se"){
    res[, c("mean", "min", "max") := .(mean(Fit), mean - se(Fit), mean + se(Fit)), by = .(Parameter, Species, Value, FitType)]	  
	}
	fitres = unique(res[,.(Species, Parameter, Value, FitType, mean, min, max)])
	fitres[, Type:='Individual']
	fitres[FitType == 'OverallFit' , Type:='Overall']
	fitres[grep('Prop', FitType), Type:='Timings']
	return(fitres)
}

```


## Standardized plots

```{r FittingPlot, echo=FALSE, fig.width=12}
pth <- file.path("C:/Users/lada/Google Drev/", resultfilename)
# pth <- file.path("~/temp/", resultfilename)
allres = fread(pth) 	
invisible({
  parameters = allres[,unique(Parameter)]
 	dt = data.table('Parameter' = allres[,unique(Parameter)], key = 'Parameter')
 	dt[, Defaultvalues:=sapply(Parameter, FUN = GetParamValue, config = cfg)]
 	res = remodel(allres, type = "minmax")
  setkey(res, Parameter)
 	DT = merge(res, dt)
  DT[, Standardized:=(Value/Defaultvalues)-1]
  DT = DT[!FitType %in% c('PropDayInSim', 'OverallFit'),]
  minmem = copy(DT)
  DT = DT[Parameter != 'GOOSE_MEM_MINMEMVALUE',]
  parameters = DT[,unique(Parameter)]})
for(i in seq_along(parameters)) {
  paramvalue = GetParamValue(parameters[i], config = cfg)
  p = ggplot(DT[Parameter == parameters[i], ], aes(Standardized, mean)) + 
    geom_vline(xintercept = 0.0, color = 'darkgrey') + 
    geom_line(aes(color = FitType)) + 
    geom_pointrange(aes(ymin = min, ymax = max, color = FitType)) +
    ggtitle('Parameter response', subtitle = paste0(ConvertParam(parameters[i]),' - default value: ', paramvalue)) +
    ylab('Fit to field data') +
    xlab('Relative change in parameter') +
    scale_color_tableau() +
    facet_grid(~Species) +
    ylim(NA, 1) +
    theme_bw()
    print(p)
}
paramvalue = GetParamValue("GOOSE_MEM_MINMEMVALUE", config = cfg)
  p = ggplot(minmem[Parameter == "GOOSE_MEM_MINMEMVALUE", ], aes(Standardized, mean)) + 
    geom_vline(xintercept = 0.0, color = 'darkgrey') + 
    geom_line(aes(color = FitType)) + 
    geom_pointrange(aes(ymin = min, ymax = max, color = FitType)) +
    ggtitle('Parameter response', subtitle = paste0(ConvertParam("GOOSE_MEM_MINMEMVALUE"),' - default value: ', paramvalue)) +
    ylab('Fit to field data') +
    xlab('Relative change in parameter') +
    scale_color_tableau() +
    facet_grid(~Species) +
    ylim(NA, 1) +
    theme_bw()
    print(p)
```

## Fitting plots

```{r ThePlots, echo=FALSE, fig.width=12}
# pdf(file = 'c:/Users/lada/Desktop/GPtoPrint2.pdf', width = 12, height = 8)
for (i in seq_along(allres[,unique(Parameter)])) {
	res = allres[Parameter == unique(Parameter)[i],]
 	param = res[,unique(Parameter)]
 	paramvalue = GetParamValue(param, config = cfg)
	res[FitType == 'PFBagOverlap', FitType:='BagOverlapPF']
	res[FitType == 'GLBagOverlap', FitType:='BagOverlapGL']
	res[FitType == 'PFTotalBag', FitType:='TotalBagPF']
	res[FitType == 'GLTotalBag', FitType:='TotalBagGL']
	res = remodel(res, type = "minmax")

	p = ggplot(res, aes(Value, mean)) +
	 geom_line(aes(color = FitType)) + 
	 geom_vline(xintercept = paramvalue, color = 'grey') +
   geom_pointrange(aes(ymin = min, ymax = max, color = FitType)) + 
	 facet_grid(Species~Type, scales = 'free_y') + 
	 scale_color_viridis(discrete=TRUE) +
	 theme(legend.text=element_text(size=10)) +
	 theme_bw() +
	 ylab('Fit')
	if(length(param) == 1) {
		p = p + ggtitle(ConvertParam(param), subtitle = paste0('Default value: ', paramvalue))
	}
	if(length(param) > 1) {
		p = p + xlab(sapply(param, FUN = ConvertParam)) + ggtitle(sapply(param, FUN = ConvertParam))
	}
	print(p)
}
# dev.off()
```


























